Enable rails-post-deploy to be run from any directory
The BASH_SOURCE variable reliably gives the path of the
script, so we can make the script work regardless of
what the current working directory is on running the
script.

diff --git a/script/rails-post-deploy b/script/rails-post-deploy
--- a/script/rails-post-deploy
+++ b/script/rails-post-deploy
@@ -11,10 +11,15 @@
 set -e
 #set -x # debug
 
-APP_DIR=`pwd`
+APP_DIR="$(readlink -f $(dirname "$BASH_SOURCE")/..)"
+cd "$APP_DIR"
 
 # make sure that there is an app directory, so are in a rails app tree
-cd app/..
+if ! [ -d app ]
+then
+    echo "Error: the 'app' directory didn't exist"
+    exit 1
+fi
 
 # read config file in for later (STAGING_SITE)
 if [ -e "config/general" ] || [ -e "config/general.yml" ]
