Add --log option
Make it possible to log the output of failed pairs, so we have some
hope of determining the cause of failure in cases where it does not
turn out to be reproducible.

diff --git a/script/spec-all-pairs b/script/spec-all-pairs
--- a/script/spec-all-pairs
+++ b/script/spec-all-pairs
@@ -3,13 +3,21 @@
 # Try all ordered pairs of spec files,
 # to winkle out order-dependent failures.
 
+log_file=/dev/null
+
 test_pair () {
     rake db:test:prepare > /dev/null 2>&1
-    if script/spec "$1" "$2" > /dev/null 2>&1
+    output=$(script/spec "$1" "$2" 2>&1)
+    if [ $? -eq 0 ]
     then
         echo "OK: $1 $2"
         return 0
     else
+        echo >> "$log_file" "FAILED: $1 $2"
+        echo >> "$log_file" "======================================="
+        echo >> "$log_file" "$output"
+        echo >> "$log_file"
+        
         echo "FAILED: $1 $2"
         return 1
     fi
@@ -57,6 +65,13 @@ pairs_from_stdin() {
     return $?
 }
 
+if [ "$1" = --log ]
+then
+  shift
+  log_file=$1
+  shift
+  cp /dev/null "$log_file"
+fi
 if [ "$1" = "-" ]
 then
     pairs_from_stdin
