Ignore non-matching lines
When reading a list of test pairs from standard input, ignore lines
that do not match the expected format

* FAILED: test1 test2

diff --git a/script/spec-all-pairs b/script/spec-all-pairs
--- a/script/spec-all-pairs
+++ b/script/spec-all-pairs
@@ -39,11 +39,18 @@ pairs_from_stdin() {
     all_okay=true
     while read line
     do
-        line=${line#\* FAILED: }
-        if ! test_pair $line
-        then
-            all_okay=false
-        fi
+        case "$line" in
+        \*\ FAILED:\ *)
+          line=${line#\* FAILED: }
+          if ! test_pair $line
+          then
+              all_okay=false
+          fi
+        ;;
+        *)
+          echo "No match: $line"
+        ;;
+        esac
     done
     
     $all_okay
